### ISSUE TITLE
Drowning damage is broken

### ISSUE THREAD

**Issue by benjaminpants** [gabehxd/PauseGameFabric#1]
I am running a Fabric server for my friends and this mod completely breaks drowning damage, below is the mod list I am using.
I'm using Minecraft 1.21 on a dedicated server, all players but me are on Bedrock edition, but the bug happens when it is just me in the server as well.
![image](https://github.com/gabehxd/PauseGameFabric/assets/27522994/09d60698-fbfb-4057-8dd9-2828df840c1f)

**Comment by benjaminpants** [comment]
Ignore the PauseGame jar being "disabled", this screenshot was taken after I learned this mod was the culprit.

**Comment by gabehxd** [comment]
Seems the air supply for entities wasn't being correctly set by the server, should be fixed with [v2.0.1](https://modrinth.com/mod/pausegamefabric/version/2.0.1)
